import classNames from "classnames";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import type React from "react";

import { Navbar } from "@/app/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={classNames(inter.className, "container mx-auto my-10")}>
				<Navbar />
				<div className="pt-10">{children}</div>
			</body>
		</html>
	);
}
